version: "3"

services:
    flask:
        build: .
        volumes:
            - ../../:/workspaces/daj
        environment:
          - FLASK_APP=server.py
          - FLASK_ENV=development
        ports:
            - "5000:5000"
        command: sleep infinity