---
kind: pipeline
type: docker
name: default

steps:
  - name: convert pdf script
    image: alpine:latest 
    environment:
      TESTENV:
        from_secret: testsecret
    commands:
    - apk add --no-cache curl bash
    - /bin/sh
    - cd ./docs/markdown/
    - echo $${TESTENV}
    - sleep 30
    - ./../../.drone/convert.sh
  - name: rm origin
    image: alpine/git
    commands:
    - git remote rm origin
  - name: commit push pdfs
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      remote: git@github.com:devinchristianson/daj.git
      branch: ${DRONE_BRANCH}
      commit: true
      commit_message: "[CI SKIP] push pdf docs"
      key: 
        from_secret: deploy_key
services:
  - name: convert
    image: thecodingmachine/gotenberg:latest
trigger:
  branch:
  - master
  event:
  - push
