---
kind: pipeline
type: docker
name: build-pdf

steps:
- name: convert
  image: alpine:latest 
  environment:
    PASSWORD:
      from_secret: file_password
    USERNAME:
      from_secret: file_username
  commands:
  - apk add --no-cache curl bash
  - /bin/sh
  - cd ./docs/markdown/
  - ./../../.drone/convert.sh
- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote_name: origin
    branch: ${DRONE_BRANCH}_pdf
    commit: true
    commit_message: "[drone ci] push pdf docs"
    force: true
    key: 
      from_secret: deploy_key
services:
- name: convert
  image: thecodingmachine/gotenberg:latest
