---
kind: pipeline
type: docker
name: default

steps:
  - name: convert pdf and uml
    image: alpine:latest 
    commands:
    - apk add --no-cache curl bash netcat-openbsd git
    - /bin/sh
    - cd ./docs/
    - ./../.drone/convert_uml_png.sh
    - ./../.drone/convert_markdown_pdf.sh
    - git remote rm origin
    - git remote add origin git@github.com:devinchristianson/daj.git
  - name: commit push pdfs and uml pngs
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: ${DRONE_BRANCH}
      commit: true
      commit_message: "[CI SKIP] push pdf docs"
      ssh_key:
        from_secret: deploy_key
services:
  - name: convertpdf
    image: thecodingmachine/gotenberg:latest
  - name: convertuml
    image: yuzutech/kroki
trigger:
  branch:
  - master
  event:
  - push
