@startuml
actor User
participant PianoGUI
participant Client
participant ChordDB
activate User
activate PianoGUI
User -> PianoGUI: select key
activate Client
PianoGUI -> Client: play key
Client -> PianoGUI: highlight key
alt if keys playing > 2
activate ChordDB
Client -> ChordDB : lookup notes
alt if chord match found
ChordDB -> Client : Chord
Client -> PianoGUI: display chord
PianoGUI -> User: chord name
else else
ChordDB -> Client : No Chord Found
deactivate ChordDB
Client -> PianoGUI: display no match
PianoGUI -> User: no match
end
Client -> PianoGUI: display no match
PianoGUI -> User: show no match
end
deactivate PianoGUI
deactivate User
@enduml
