@startuml
actor User
participant PianoGUI
participant Client
participant ExcerciseDB
activate User
activate PianoGUI
User -> PianoGUI: select progression excercise
PianoGUI -> Client: find excercise
Client -> ExcerciseDB: retrieve excercise
ExcerciseDB -> Client: return excercise
Client -> PianoGUI: display progression form
User -> PianoGUI: answer
PianoGUI -> Client: measure accuracy
Client -> PianoGUI: display result
alt if satisfied with answer
User -> PianoGUI: retry
else else
User -> PianoGUI: next excercise
end
deactivate PianoGUI
deactivate User
@enduml
