@startuml
actor User
participant GUI
participant GoogleSSO
participant Client
participant Backend
activate User
activate GUI
User -> GUI: select Sign-in
activate GoogleSSO
GUI -> GoogleSSO: SignOn()
User -> GoogleSSO: Sign-in with Google Account
activate Client
GoogleSSO -> Client: onSignIn(googleUser) : token
deactivate GoogleSSO
Client -> Backend: verify(token) : boolean
alt true
activate Backend
Backend -> Client: pass(user-data) : user-data
Client -> GUI: login success
GUI -> User: login success
else false
Backend -> Client: token invalid
deactivate Backend
Client -> GUI: login failure
deactivate Client
GUI -> User: login failed
deactivate GUI
deactivate User
end
@enduml
